apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://flask-service:5500;
        }
        location /hello {
          return 200 "Hello World";
        }
        location /greeting {
          return 200 "Thanks for visiting this page";
        }
        location /leave {
        return 200 "You may go now!!!";
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx/